runtime: python39

env_variables:
  GCS_BUCKET: "framepickr-ai-images"
  GCS_BASE_URL: "https://storage.googleapis.com"
  PORT: 8080

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto

